############################################
##                Lets Encrypt            ##
############################################
###### AUTOMATIONS -------------------------
automation:
  - alias: "Lets Encrypt Renewal"
    initial_state: 'on'
    trigger:
    - platform: time
      at: '00:00:00'
    action:
    - service: hassio.addon_restart
      data:
        addon: core_letsencrypt
